"""一对多数据库操作

Revision ID: 093398133236
Revises: 5931dd6e8e36
Create Date: 2025-11-05 09:12:43.292943

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '093398133236'
down_revision = '5931dd6e8e36'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_extension',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('birthday', sa.Date(), nullable=False),
    sa.Column('university', sa.String(length=100), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_user_extension_user_id_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_extension'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_extension')
    # ### end Alembic commands ###
