"""多对多数据库实现

Revision ID: 5931dd6e8e36
Revises: b8d141fb330a
Create Date: 2025-11-03 19:32:05.039578

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5931dd6e8e36'
down_revision = 'b8d141fb330a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('permission',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_permission'))
    )
    op.create_table('department_permission',
    sa.Column('department_id', sa.Integer(), nullable=False),
    sa.Column('permission_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['department.id'], name=op.f('fk_department_permission_department_id_department')),
    sa.ForeignKeyConstraint(['permission_id'], ['permission.id'], name=op.f('fk_department_permission_permission_id_permission')),
    sa.PrimaryKeyConstraint('department_id', 'permission_id', name=op.f('pk_department_permission'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('department_permission')
    op.drop_table('permission')
    # ### end Alembic commands ###
