"""empty message

Revision ID: a8f9fedb696c
Revises: 093398133236
Create Date: 2025-11-05 09:25:31.476824

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a8f9fedb696c'
down_revision = '093398133236'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_extension', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_user_extension_user_id'), ['user_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_extension', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_user_extension_user_id'), type_='unique')

    # ### end Alembic commands ###
